package main;

import java.sql.Date;

public class Rental {
	
	//Properties//
	

//	private enum area {
//		Kelowna,Penticton,BlackMountain,DilworthMountain,Ellison,Glenmore,
//		JoeRich,KelownaNorth,KelownaSouth,LowerMission,NorthGlenmore,RutlandNorth,
//		RutlandSouth,KelownaSouthEast,SpringfieldSpall,UpperMission
//	}
	
	private String area = "Not available";	
	private int Rid;
	private String price = "Contact for price";
	private String title = "Rental";
	private String description = "No description available";
	private String address = "Address not available";
	private String link = "No link available";
	
	//Note sql.Date is used instead of util.Date
	private Date date;
	
	private Contact owner;
	
	
	@Override
	public String toString(){
		String s = String.format("Link:\t%s\nTitle:\t%s\nAddress:\t%s\nPrice:\t%s\nDescription:\t%s\nArea:\t%s\n", link,title,address,price,description,area);
		return s;
		
	}
	
	
	
	//Setters and Getters	
	
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public int getRid() {
		return Rid;
	}

	//RID is generated automatically upon insertion into the database so we probably shouldn't touch it here
	public void setRid(int rid) {
		Rid = rid;
	}

	public Date getDate() {
		return date;
	}

	//Date is also generated by the database upon insertion 
	public void setDate(Date date) {
		this.date = date;
	}
	
	
	public Contact getContact() {
		return owner;
	}

	public void setContact(Contact c) {
		this.owner = c;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	
}
